use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const MAX_DESCRIPTION_CHARS: usize = 100;
const MAX_BODY_BYTES: usize = 4 * 1024;

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let skills_dir = manifest_dir.join("data/skills");
    println!("cargo:rerun-if-changed={}", skills_dir.display());

    let mut skill_dirs = read_dirs(&skills_dir);
    skill_dirs.sort();

    let mut generated =
        String::from("// Generated by build.rs. Edit data/skills, not this file.\n\n");
    generated.push_str("pub const BUILTIN_SKILLS: &[BuiltinSkill] = &[\n");

    for skill_dir in skill_dirs {
        let name = skill_dir
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_else(|| {
                panic!("built-in skill directory is not valid UTF-8: {skill_dir:?}")
            });
        validate_component(name, "skill name");

        let skill_md = skill_dir.join("SKILL.md");
        let skill_text = fs::read_to_string(&skill_md)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", skill_md.display()));
        validate_skill_metadata(name, &skill_text, &skill_md);

        let mut files = Vec::new();
        collect_files(&skill_dir, &skill_dir, &mut files);
        files.sort();
        if files.is_empty() {
            panic!("built-in skill {name:?} has no files");
        }
        if let Some(interface_path) = files
            .iter()
            .find(|path| path.as_str() == "agents/openai.yaml")
        {
            validate_interface_description(
                &skill_dir.join(interface_path),
                &fs::read_to_string(skill_dir.join(interface_path)).unwrap_or_else(|error| {
                    panic!("cannot read agents/openai.yaml for {name:?}: {error}")
                }),
            );
        }

        generated.push_str("    BuiltinSkill {\n");
        generated.push_str(&format!("        name: {:?},\n", name));
        generated.push_str("        files: &[\n");
        for relative in files {
            let source = skill_dir.join(&relative);
            println!("cargo:rerun-if-changed={}", source.display());
            let executable = is_executable(&source);
            generated.push_str("            BuiltinSkillFile {\n");
            generated.push_str(&format!("                relative_path: {:?},\n", relative));
            let source_suffix = format!("/data/skills/{name}/{relative}");
            generated.push_str(&format!(
                "                contents: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?})),\n",
                source_suffix
            ));
            generated.push_str(&format!("                executable: {executable},\n"));
            generated.push_str("            },\n");
        }
        generated.push_str("        ],\n    },\n");
    }

    generated.push_str("];\n");
    let output = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("builtin_skills.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", output.display()));
}

fn read_dirs(path: &Path) -> Vec<PathBuf> {
    let entries = fs::read_dir(path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
    entries
        .map(|entry| {
            let entry =
                entry.unwrap_or_else(|error| panic!("cannot read a data/skills entry: {error}"));
            let path = entry.path();
            let metadata = fs::symlink_metadata(&path)
                .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", path.display()));
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                panic!("data/skills may contain only skill directories: {path:?}");
            }
            path
        })
        .collect()
}

fn collect_files(root: &Path, current: &Path, output: &mut Vec<String>) {
    let entries = fs::read_dir(current)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", current.display()));
    for entry in entries {
        let entry = entry.unwrap_or_else(|error| panic!("cannot read a skill entry: {error}"));
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)
            .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", path.display()));
        if metadata.file_type().is_symlink() {
            panic!("built-in skills may not contain symlinks: {path:?}");
        }
        if metadata.is_dir() {
            collect_files(root, &path, output);
        } else if metadata.is_file() {
            let relative = path
                .strip_prefix(root)
                .unwrap_or_else(|_| panic!("{} escaped {}", path.display(), root.display()));
            let relative = relative
                .to_str()
                .unwrap_or_else(|| panic!("skill path is not valid UTF-8: {relative:?}"))
                .replace('\\', "/");
            for component in relative.split('/') {
                validate_component(component, "skill file path component");
            }
            output.push(relative);
        } else {
            panic!("built-in skills may contain only regular files and directories: {path:?}");
        }
    }
}

fn validate_component(component: &str, label: &str) {
    if component.is_empty()
        || component == "."
        || component == ".."
        || component.contains('\0')
        || component.contains('"')
        || component.contains('\\')
    {
        panic!("invalid {label}: {component:?}");
    }
}

fn validate_skill_metadata(name: &str, text: &str, path: &Path) {
    let mut lines = text.lines();
    if lines.next() != Some("---") {
        panic!("{} must start with YAML frontmatter", path.display());
    }

    let mut metadata = Vec::new();
    let mut closed = false;
    for line in lines {
        if line.trim() == "---" {
            closed = true;
            break;
        }
        metadata.push(line);
    }
    if !closed {
        panic!("{} has unclosed YAML frontmatter", path.display());
    }

    let value = |key: &str| {
        metadata.iter().find_map(|line| {
            let (candidate, value) = line.split_once(':')?;
            (candidate.trim() == key).then(|| value.trim().trim_matches('"').trim_matches('\''))
        })
    };

    if value("name") != Some(name) {
        panic!("{} must declare name: {name}", path.display());
    }
    let description = value("description")
        .filter(|description| !description.is_empty())
        .unwrap_or_else(|| panic!("{} must declare a description", path.display()));
    let chars = description.chars().count();
    if chars > MAX_DESCRIPTION_CHARS {
        panic!(
            "{} description is {chars} characters; the maximum is {MAX_DESCRIPTION_CHARS}",
            path.display()
        );
    }

    let body = text
        .strip_prefix("---\n")
        .and_then(|rest| rest.split_once("\n---\n"))
        .map(|(_, body)| body.trim())
        .unwrap_or_default();
    if body.as_bytes().len() > MAX_BODY_BYTES {
        panic!(
            "{} body is {} bytes; the maximum is {MAX_BODY_BYTES}",
            path.display(),
            body.len()
        );
    }
}

fn validate_interface_description(path: &Path, text: &str) {
    let Some(description) = text.lines().find_map(|line| {
        let (key, value) = line.split_once(':')?;
        (key.trim() == "short_description")
            .then(|| value.trim().trim_matches('"').trim_matches('\''))
    }) else {
        return;
    };
    let chars = description.chars().count();
    if chars > MAX_DESCRIPTION_CHARS {
        panic!(
            "{} short_description is {chars} characters; the maximum is {MAX_DESCRIPTION_CHARS}",
            path.display()
        );
    }
}

#[cfg(unix)]
fn is_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    fs::metadata(path)
        .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", path.display()))
        .permissions()
        .mode()
        & 0o111
        != 0
}

#[cfg(not(unix))]
fn is_executable(_path: &Path) -> bool {
    false
}
