use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

const MAX_DESCRIPTION_CHARS: usize = 100;
const MAX_BODY_BYTES: usize = 4 * 1024;

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    emit_build_metadata(&manifest_dir);

    let skills_dir = manifest_dir.join("data/skills");
    println!("cargo:rerun-if-changed={}", skills_dir.display());

    let mut skill_dirs = read_dirs(&skills_dir);
    skill_dirs.sort();

    let mut generated =
        String::from("// Generated by build.rs. Edit data/skills, not this file.\n\n");
    generated.push_str("pub const BUILTIN_SKILLS: &[BuiltinSkill] = &[\n");

    for skill_dir in skill_dirs {
        let name = skill_dir
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_else(|| {
                panic!("built-in skill directory is not valid UTF-8: {skill_dir:?}")
            });
        validate_skill_name(name);

        let skill_md = skill_dir.join("SKILL.md");
        let skill_text = fs::read_to_string(&skill_md)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", skill_md.display()));
        validate_skill_metadata(name, &skill_text, &skill_md);

        let mut files = Vec::new();
        collect_files(&skill_dir, &skill_dir, &mut files);
        files.sort();
        if files.is_empty() {
            panic!("built-in skill {name:?} has no files");
        }
        if files.iter().any(|path| path == "agents/openai.yaml") {
            panic!("built-in skill {name:?} must not include agents/openai.yaml");
        }

        generated.push_str("    BuiltinSkill {\n");
        generated.push_str(&format!("        name: {:?},\n", name));
        generated.push_str("        files: &[\n");
        for relative in files {
            let source = skill_dir.join(&relative);
            println!("cargo:rerun-if-changed={}", source.display());
            let executable = is_executable(&source);
            generated.push_str("            BuiltinSkillFile {\n");
            generated.push_str(&format!("                relative_path: {:?},\n", relative));
            let source_suffix = format!("/data/skills/{name}/{relative}");
            generated.push_str(&format!(
                "                contents: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?})),\n",
                source_suffix
            ));
            generated.push_str(&format!("                executable: {executable},\n"));
            generated.push_str("            },\n");
        }
        generated.push_str("        ],\n    },\n");
    }

    generated.push_str("];\n");
    let output = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("builtin_skills.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", output.display()));
}

fn emit_build_metadata(manifest_dir: &Path) {
    println!("cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH");
    println!("cargo:rerun-if-env-changed=TERA_GIT_SHA");

    let commit_sha = env::var("TERA_GIT_SHA")
        .ok()
        .filter(|sha| !sha.trim().is_empty())
        .unwrap_or_else(|| {
            git_output(manifest_dir, &["rev-parse", "HEAD"])
                .unwrap_or_else(|| "unknown".to_string())
        });

    // HEAD itself usually contains only the name of the current branch. Watching
    // its resolved ref makes a commit rebuild the metadata even when no source
    // file changed after the last verification build.
    if let Some(git_dir) = git_output(manifest_dir, &["rev-parse", "--absolute-git-dir"]) {
        println!("cargo:rerun-if-changed={git_dir}/HEAD");
        if let Some(reference) = git_output(manifest_dir, &["symbolic-ref", "-q", "HEAD"]) {
            println!("cargo:rerun-if-changed={git_dir}/{reference}");
        }
    }

    let built_at = env::var("SOURCE_DATE_EPOCH")
        .ok()
        .and_then(|value| value.parse::<u64>().ok())
        .unwrap_or_else(|| {
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("system clock is before the Unix epoch")
                .as_secs()
        });

    println!("cargo:rustc-env=TERA_GIT_SHA={commit_sha}");
    println!("cargo:rustc-env=TERA_BUILD_TIME={}", rfc3339(built_at));
    println!(
        "cargo:rustc-env=TERA_BUILD_TARGET={}",
        env::var("TARGET").unwrap_or_else(|_| "unknown".to_string())
    );
}

fn git_output(manifest_dir: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .args(args)
        .current_dir(manifest_dir)
        .output()
        .ok()?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).trim().to_string())
        .filter(|value| !value.is_empty())
}

/// Format a Unix timestamp without adding a build dependency solely for a date.
fn rfc3339(timestamp: u64) -> String {
    let days = (timestamp / 86_400) as i64;
    let seconds = timestamp % 86_400;
    let (year, month, day) = civil_from_days(days);
    let hour = seconds / 3_600;
    let minute = seconds % 3_600 / 60;
    let second = seconds % 60;
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z")
}

// Howard Hinnant's civil calendar conversion, with the Unix epoch as day zero.
fn civil_from_days(days_since_epoch: i64) -> (i64, i64, i64) {
    let z = days_since_epoch + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1_460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let mut year = year_of_era + era * 400;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_prime = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_prime + 2) / 5 + 1;
    let month = month_prime + if month_prime < 10 { 3 } else { -9 };
    year += i64::from(month <= 2);
    (year, month, day)
}

fn read_dirs(path: &Path) -> Vec<PathBuf> {
    let entries = fs::read_dir(path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
    entries
        .map(|entry| {
            let entry =
                entry.unwrap_or_else(|error| panic!("cannot read a data/skills entry: {error}"));
            let path = entry.path();
            let metadata = fs::symlink_metadata(&path)
                .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", path.display()));
            if metadata.file_type().is_symlink() || !metadata.is_dir() {
                panic!("data/skills may contain only skill directories: {path:?}");
            }
            path
        })
        .collect()
}

/// Names that appear inside a skill directory without anyone putting them there.
///
/// Embedding one is worse than untidy. `WorkspaceInit` reads any edit inside a
/// built-in skill as the user adopting it and freezes that skill at its current
/// version, so a `.pyc` that regenerates the first time somebody runs the script
/// would stop the skill ever being updated again.
const LOCAL_BYPRODUCTS: &[&str] = &["__pycache__", ".DS_Store"];

fn collect_files(root: &Path, current: &Path, output: &mut Vec<String>) {
    let entries = fs::read_dir(current)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", current.display()));
    for entry in entries {
        let entry = entry.unwrap_or_else(|error| panic!("cannot read a skill entry: {error}"));
        let path = entry.path();
        if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| LOCAL_BYPRODUCTS.contains(&name))
        {
            continue;
        }
        let metadata = fs::symlink_metadata(&path)
            .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", path.display()));
        if metadata.file_type().is_symlink() {
            panic!("built-in skills may not contain symlinks: {path:?}");
        }
        if metadata.is_dir() {
            collect_files(root, &path, output);
        } else if metadata.is_file() {
            let relative = path
                .strip_prefix(root)
                .unwrap_or_else(|_| panic!("{} escaped {}", path.display(), root.display()));
            let relative = relative
                .to_str()
                .unwrap_or_else(|| panic!("skill path is not valid UTF-8: {relative:?}"))
                .replace('\\', "/");
            for component in relative.split('/') {
                validate_component(component, "skill file path component");
            }
            output.push(relative);
        } else {
            panic!("built-in skills may contain only regular files and directories: {path:?}");
        }
    }
}

fn validate_component(component: &str, label: &str) {
    if component.is_empty()
        || component == "."
        || component == ".."
        || component.contains('\0')
        || component.contains('"')
        || component.contains('\\')
    {
        panic!("invalid {label}: {component:?}");
    }
}

fn validate_skill_metadata(name: &str, text: &str, path: &Path) {
    let mut lines = text.lines();
    if lines.next() != Some("---") {
        panic!("{} must start with YAML frontmatter", path.display());
    }

    let mut metadata = Vec::new();
    let mut closed = false;
    for line in lines {
        if line.trim() == "---" {
            closed = true;
            break;
        }
        metadata.push(line);
    }
    if !closed {
        panic!("{} has unclosed YAML frontmatter", path.display());
    }

    let value = |key: &str| frontmatter_value(&metadata, key);

    if value("name").as_deref() != Some(name) {
        panic!("{} must declare name: {name}", path.display());
    }
    let description = value("description")
        .filter(|description| !description.is_empty())
        .unwrap_or_else(|| panic!("{} must declare a description", path.display()));
    let chars = description.chars().count();
    if chars > MAX_DESCRIPTION_CHARS {
        panic!(
            "{} description is {chars} characters; the maximum is {MAX_DESCRIPTION_CHARS}",
            path.display()
        );
    }

    let body = text
        .strip_prefix("---\n")
        .and_then(|rest| rest.split_once("\n---\n"))
        .map(|(_, body)| body.trim())
        .unwrap_or_default();
    if body.len() > MAX_BODY_BYTES {
        panic!(
            "{} body is {} bytes; the maximum is {MAX_BODY_BYTES}",
            path.display(),
            body.len()
        );
    }
}

fn frontmatter_value(lines: &[&str], key: &str) -> Option<String> {
    for (index, line) in lines.iter().enumerate() {
        let Some((candidate, raw)) = line.split_once(':') else {
            continue;
        };
        if candidate.trim() != key {
            continue;
        }
        let raw = raw.trim();
        if raw == "|" || raw == ">" {
            let mut value = String::new();
            for continuation in lines.iter().skip(index + 1) {
                if !continuation.starts_with([' ', '\t']) {
                    break;
                }
                if !value.is_empty() {
                    value.push(' ');
                }
                value.push_str(continuation.trim());
            }
            return Some(value);
        }
        return Some(raw.trim_matches('"').trim_matches('\'').to_string());
    }
    None
}

fn validate_skill_name(name: &str) {
    if name.is_empty()
        || name.len() > 64
        || !name.chars().all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        })
        || !name
            .chars()
            .next()
            .is_some_and(|character| character.is_ascii_lowercase() || character.is_ascii_digit())
    {
        panic!("invalid native skill name {name:?}; use lowercase letters, digits, and hyphens");
    }
}

#[cfg(unix)]
fn is_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    fs::metadata(path)
        .unwrap_or_else(|error| panic!("cannot inspect {}: {error}", path.display()))
        .permissions()
        .mode()
        & 0o111
        != 0
}

#[cfg(not(unix))]
fn is_executable(_path: &Path) -> bool {
    false
}
