// Auto-generated by FORGE - DO NOT EDIT

import { getForgeClient, createJobStore } from "@forge/svelte";
import type { ProcessWhatsappMessageJobInput } from "./types";

// Jobs
export const trackProcessWhatsappMessageJob = (
  args: ProcessWhatsappMessageJobInput,
) =>
  createJobStore<ProcessWhatsappMessageJobInput, void>(
    "process_whatsapp_message_job",
    args,
  );
