// Auto-generated by FORGE - DO NOT EDIT
// Run `forge generate` after adding functions to src/functions/

// Function bindings will be generated here based on your Rust functions
// Example:
// import { createQuery, createMutation } from "@forge/svelte";
// import type { User } from "./types";
// export const getUsers = createQuery<null, User[]>("get_users");
// export const createUser = createMutation<{ name: string }, User>("create_user");

export {};
