// Auto-generated by FORGE - DO NOT EDIT
import type { SubscriptionStore } from "@forge/svelte";
import type { SubscriptionResult } from "@forge/svelte";

export interface ReactiveQuery<T> extends SubscriptionResult<T> {
  unsubscribe: () => void;
}

export function toReactive<T>(store: SubscriptionStore<T>): ReactiveQuery<T> {
  const state: ReactiveQuery<T> = $state({
    loading: true,
    data: null,
    error: null,
    stale: false,
    unsubscribe: () => {
      unsubscribeCallback();
      store.unsubscribe();
    },
  });

  const unsubscribeCallback = store.subscribe((s) => {
    state.loading = s.loading;
    state.data = s.data;
    state.error = s.error;
    state.stale = s.stale;
  });

  return state;
}
