// Auto-generated by FORGE - DO NOT EDIT
// Run `forge generate` after adding or modifying models

// Model types will be generated here based on your Rust schema
// Example: export interface User { id: string; name: string; }

// Common types (re-exported from @forge/svelte for convenience)
export type {
  ForgeError,
  QueryResult,
  SubscriptionResult,
} from "@forge/svelte";
