// Auto-generated by FORGE - DO NOT EDIT

export interface ProcessWhatsappMessageJobInput {
  message_id: string;
}

export interface RpcError {
  code: string;
  message: string;
}

export interface RpcResponse {
  success: boolean;
  data?: Value;
  error?: RpcError;
}

export interface WhatsappMessage {
  id: string;
  chat_id: string;
  direction: MessageDirection;
  agent_id?: string;
  status: MessageStatus;
  content_text?: string;
  media?: Value;
  embedding?: f32[];
  metadata: unknown;
  created_at: string;
  updated_at: string;
}

export type {
  ForgeError,
  QueryResult,
  SubscriptionResult,
} from "@forge/svelte";
