// Auto-generated by FORGE v0.2.1 - DO NOT EDIT
// Regenerate with: forge generate

import { getContext, setContext } from "svelte";
import type { ForgeClient } from "./client.js";
import type { AuthState } from "./types.js";

const FORGE_CLIENT_KEY = Symbol("forge-client");
const FORGE_AUTH_KEY = Symbol("forge-auth");
let globalClient: ForgeClient | null = null;

export function getForgeClient(): ForgeClient {
  try {
    const client = getContext<ForgeClient>(FORGE_CLIENT_KEY);
    if (client) return client;
  } catch {}
  if (globalClient) return globalClient;
  throw new Error(
    "FORGE client not found. Wrap your component with ForgeProvider.",
  );
}

export function setForgeClient(client: ForgeClient): void {
  setContext(FORGE_CLIENT_KEY, client);
  globalClient = client;
}

export function getAuthState(): AuthState {
  const auth = getContext<AuthState>(FORGE_AUTH_KEY);
  if (!auth) throw new Error("Auth state not found.");
  return auth;
}

export function setAuthState(auth: AuthState): void {
  setContext(FORGE_AUTH_KEY, auth);
}
