// Auto-generated by FORGE v0.2.1 - DO NOT EDIT
// Regenerate with: forge generate

type DateInput = string | Date;

interface FormatOptions {
  date?: "short" | "medium" | "long" | "full";
  time?: "short" | "medium" | "long" | "full";
  locale?: string;
}

function toDate(input: DateInput): Date {
  const date = typeof input === "string" ? new Date(input) : input;
  if (isNaN(date.getTime())) {
    throw new Error(`Invalid date: ${input}`);
  }
  return date;
}

/**
 * Date/time utilities for working with Forge datetime types.
 * All datetime values are ISO 8601 strings on the wire.
 */
export const dt = {
  /**
   * Returns current UTC timestamp as ISO string.
   */
  now(): string {
    return new Date().toISOString();
  },

  /**
   * Parses an ISO date string into a Date object.
   */
  parse(input: string): Date {
    return new Date(input);
  },

  /**
   * Formats a date for display using Intl.DateTimeFormat.
   */
  format(input: DateInput, options: FormatOptions = {}): string {
    const date = toDate(input);
    const locale = options.locale ?? "en-US";

    if (options.date && options.time) {
      return new Intl.DateTimeFormat(locale, {
        dateStyle: options.date,
        timeStyle: options.time,
      }).format(date);
    }

    if (options.date) {
      return new Intl.DateTimeFormat(locale, {
        dateStyle: options.date,
      }).format(date);
    }

    if (options.time) {
      return new Intl.DateTimeFormat(locale, {
        timeStyle: options.time,
      }).format(date);
    }

    return new Intl.DateTimeFormat(locale, {
      dateStyle: "medium",
      timeStyle: "short",
    }).format(date);
  },

  /**
   * Returns a human-readable relative time string using Intl.RelativeTimeFormat.
   */
  relative(input: DateInput, baseDate: DateInput = new Date()): string {
    const date = toDate(input);
    const base = toDate(baseDate);
    const diffMs = date.getTime() - base.getTime();
    const diffSec = Math.round(diffMs / 1000);
    const diffMin = Math.round(diffSec / 60);
    const diffHr = Math.round(diffMin / 60);
    const diffDay = Math.round(diffHr / 24);
    const diffWeek = Math.round(diffDay / 7);
    const diffMonth = Math.round(diffDay / 30);
    const diffYear = Math.round(diffDay / 365);

    const rtf = new Intl.RelativeTimeFormat("en", { numeric: "auto" });

    if (Math.abs(diffSec) < 60) return rtf.format(diffSec, "second");
    if (Math.abs(diffMin) < 60) return rtf.format(diffMin, "minute");
    if (Math.abs(diffHr) < 24) return rtf.format(diffHr, "hour");
    if (Math.abs(diffDay) < 7) return rtf.format(diffDay, "day");
    if (Math.abs(diffWeek) < 4) return rtf.format(diffWeek, "week");
    if (Math.abs(diffMonth) < 12) return rtf.format(diffMonth, "month");
    return rtf.format(diffYear, "year");
  },
};
