<!--
  Auto-generated by FORGE v0.2.1 - DO NOT EDIT
  Regenerate with: forge generate
-->
<script lang="ts">
  import { onMount, onDestroy, type Snippet } from 'svelte';
  import { createForgeClient } from './client.js';
  import { setForgeClient, setAuthState } from './context.js';
  import type { AuthState, ConnectionState } from './types.js';

  interface Props {
    url: string;
    getToken?: () => string | null | Promise<string | null>;
    onConnectionChange?: (state: ConnectionState) => void;
    children: Snippet;
  }

  let props: Props = $props();

  const client = createForgeClient({
    url: props.url,
    getToken: props.getToken,
  });

  setForgeClient(client);

  const authState: AuthState = $state({ user: null, token: null, loading: true });
  setAuthState(authState);

  onMount(() => {
    const unsubscribe = client.onConnectionStateChange((state) => {
      props.onConnectionChange?.(state);
    });

    // Connect handles token resolution internally before establishing SSE
    client.connect().then(async () => {
      if (props.getToken) {
        authState.token = await props.getToken();
      }
      authState.loading = false;
    }).catch(() => {
      authState.loading = false;
    });

    return unsubscribe;
  });

  onDestroy(() => client.disconnect());
</script>

{@render props.children()}
