// Auto-generated by FORGE v0.2.1 - DO NOT EDIT
// Regenerate with: forge generate

export interface ForgeError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface QueryResult<T> {
  loading: boolean;
  data: T | null;
  error: ForgeError | null;
}

export interface SubscriptionResult<T> extends QueryResult<T> {
  stale: boolean;
}

export type ConnectionState = "disconnected" | "connecting" | "connected";

export interface AuthState {
  user: unknown | null;
  token: string | null;
  loading: boolean;
}

export type JobStatus =
  | "pending"
  | "claimed"
  | "running"
  | "completed"
  | "retry"
  | "failed"
  | "dead_letter"
  | "cancel_requested"
  | "cancelled"
  | "not_found";

export interface JobState<TOutput = unknown> {
  jobId: string;
  status: JobStatus;
  progress: number | null;
  message: string | null;
  output: TOutput | null;
  error: string | null;
}

export type WorkflowStatus =
  | "created"
  | "running"
  | "waiting"
  | "completed"
  | "compensating"
  | "compensated"
  | "failed"
  | "not_found";

export interface WorkflowStepState {
  name: string;
  status: "pending" | "running" | "completed" | "failed" | "compensated" | "skipped";
  error: string | null;
}

export interface WorkflowState<TOutput = unknown> {
  workflowId: string;
  status: WorkflowStatus;
  step: string | null;
  waitingFor: string | null;
  steps: WorkflowStepState[];
  output: TOutput | null;
  error: string | null;
}
